/**
 * My API
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Operario { 
    id?: string;
    numeroEmpleado?: string;
    DNI?: string;
    nombre?: string;
    apellido?: string;
    telefono?: string;
    nombreUsuario?: string;
    contrasea?: string;
    email?: string;
}
