/**
 * My API
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Tarea { 
    id?: string;
    descripcion?: string;
    nombre?: string;
    fechaInicio?: string;
    fechaFin?: string;
    tipoDeTarea?: any;
    sector?: any;
    idOperario?: string;
    estado?: Array<any>;
}
