export * from './cliente.service';
import { ClienteService } from './cliente.service';
export * from './empleado.service';
import { EmpleadoService } from './empleado.service';
export * from './estado.service';
import { EstadoService } from './estado.service';
export * from './operario.service';
import { OperarioService } from './operario.service';
export * from './orden.service';
import { OrdenService } from './orden.service';
export * from './oti.service';
import { OtiService } from './oti.service';
export * from './rosca.service';
import { RoscaService } from './rosca.service';
export * from './sector.service';
import { SectorService } from './sector.service';
export * from './supervisor.service';
import { SupervisorService } from './supervisor.service';
export * from './tarea.service';
import { TareaService } from './tarea.service';
export const APIS = [ClienteService, EmpleadoService, EstadoService, OperarioService, OrdenService, OtiService, RoscaService, SectorService, SupervisorService, TareaService];
