/**
 * My API
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { CambioEstado } from '../model/cambioEstado';
import { Estados } from '../model/estados';
import { Tareas } from '../model/tareas';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';


@Injectable()
export class EstadoService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Endpoint para obtener las tareas asigandas de un operario.
     * @param id ID de operario.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public estadoIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<Tareas>;
    public estadoIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tareas>>;
    public estadoIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tareas>>;
    public estadoIdGet(id: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling estadoIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Tareas>(`${this.basePath}/estado/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para modificar el estado.
     * @param cambioEstado datos para modificar el estado de una tarea, esto puede generar el cambio de esatdo de la oti y de sector
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public estadoPut(cambioEstado: CambioEstado, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public estadoPut(cambioEstado: CambioEstado, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public estadoPut(cambioEstado: CambioEstado, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public estadoPut(cambioEstado: CambioEstado, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (cambioEstado === null || cambioEstado === undefined) {
            throw new Error('Required parameter cambioEstado was null or undefined when calling estadoPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/estado/`,
            cambioEstado,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para obtener los tipos de estado.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public estadoTipoEstadoGet(observe?: 'body', reportProgress?: boolean): Observable<Estados>;
    public estadoTipoEstadoGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Estados>>;
    public estadoTipoEstadoGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Estados>>;
    public estadoTipoEstadoGet(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Estados>(`${this.basePath}/estado/tipoEstado`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
