/**
 * My API
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { ArrayOti } from '../model/arrayOti';
import { ArrayRoscas } from '../model/arrayRoscas';
import { ArraySector } from '../model/arraySector';
import { Ordenes } from '../model/ordenes';
import { Oti } from '../model/oti';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';


@Injectable()
export class OtiService {

    protected basePath = 'http://localhost:8081';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Endpoint para actulizar orden 
     * @param oti datos para actulizar una oti
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiActualizarOrdenPut(oti: Oti, observe?: 'body', reportProgress?: boolean): Observable<Oti>;
    public otiActualizarOrdenPut(oti: Oti, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Oti>>;
    public otiActualizarOrdenPut(oti: Oti, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Oti>>;
    public otiActualizarOrdenPut(oti: Oti, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (oti === null || oti === undefined) {
            throw new Error('Required parameter oti was null or undefined when calling otiActualizarOrdenPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Oti>(`${this.basePath}/oti/actualizarOrden`,
            oti,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para crear una oti con sus datos basicos.
     * @param oti datos para crear una oti
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiDatosBasicosPost(oti: Oti, observe?: 'body', reportProgress?: boolean): Observable<Oti>;
    public otiDatosBasicosPost(oti: Oti, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Oti>>;
    public otiDatosBasicosPost(oti: Oti, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Oti>>;
    public otiDatosBasicosPost(oti: Oti, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (oti === null || oti === undefined) {
            throw new Error('Required parameter oti was null or undefined when calling otiDatosBasicosPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Oti>(`${this.basePath}/oti/datosBasicos`,
            oti,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para obtener las otis.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiGet(observe?: 'body', reportProgress?: boolean): Observable<ArrayOti>;
    public otiGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ArrayOti>>;
    public otiGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ArrayOti>>;
    public otiGet(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ArrayOti>(`${this.basePath}/oti/`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para obtener una oti.
     * @param id oti ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<Oti>;
    public otiIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Oti>>;
    public otiIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Oti>>;
    public otiIdGet(id: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling otiIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Oti>(`${this.basePath}/oti/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint filtra ordenes por fecha.
     * @param fecha fecha creacion orden de produccion
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiObtenerOrdenesFechaGet(fecha: string, observe?: 'body', reportProgress?: boolean): Observable<Ordenes>;
    public otiObtenerOrdenesFechaGet(fecha: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Ordenes>>;
    public otiObtenerOrdenesFechaGet(fecha: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Ordenes>>;
    public otiObtenerOrdenesFechaGet(fecha: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (fecha === null || fecha === undefined) {
            throw new Error('Required parameter fecha was null or undefined when calling otiObtenerOrdenesFechaGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Ordenes>(`${this.basePath}/oti/obtenerOrdenes/${encodeURIComponent(String(fecha))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para obtener las roscas de una orden.
     * @param idOrden orden ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiObtenerRoscasIdOrdenGet(idOrden: string, observe?: 'body', reportProgress?: boolean): Observable<ArrayRoscas>;
    public otiObtenerRoscasIdOrdenGet(idOrden: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ArrayRoscas>>;
    public otiObtenerRoscasIdOrdenGet(idOrden: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ArrayRoscas>>;
    public otiObtenerRoscasIdOrdenGet(idOrden: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (idOrden === null || idOrden === undefined) {
            throw new Error('Required parameter idOrden was null or undefined when calling otiObtenerRoscasIdOrdenGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ArrayRoscas>(`${this.basePath}/oti/obtenerRoscas/${encodeURIComponent(String(idOrden))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para obtener las otis asigandas de un sector.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiSectoresGet(observe?: 'body', reportProgress?: boolean): Observable<ArraySector>;
    public otiSectoresGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ArraySector>>;
    public otiSectoresGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ArraySector>>;
    public otiSectoresGet(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<ArraySector>(`${this.basePath}/oti/sectores`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Endpoint para actulizar sectores y tareas.
     * @param oti datos para actulizar una oti
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public otiSectoresYTareasPut(oti: Oti, observe?: 'body', reportProgress?: boolean): Observable<Oti>;
    public otiSectoresYTareasPut(oti: Oti, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Oti>>;
    public otiSectoresYTareasPut(oti: Oti, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Oti>>;
    public otiSectoresYTareasPut(oti: Oti, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (oti === null || oti === undefined) {
            throw new Error('Required parameter oti was null or undefined when calling otiSectoresYTareasPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Oti>(`${this.basePath}/oti/sectoresYTareas`,
            oti,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
